[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
mio = "0.8.8"
thiserror = "1.0"
thunderdome = "0.6.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-test = "0.2.4"
uuid = "1.4"
stewart = { version = "0.9.0", path = "./crates/stewart" }
