[package]
name = "stewart-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
stewart.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
