[package]
name = "stewart-utils"
version = "0.4.0"
edition = "2021"
description = "Small common utilities for stewart"
readme = "../../README.md"
repository = "https://github.com/open-mv-sandbox/stewart"
license = "MIT OR Apache-2.0"

[dependencies]
stewart.workspace = true
